export const TABLE_COLS = {
  proc: [
    { key: 'session_id',          label: 'Session',     type: 'num'   },
    { key: 'login_name',          label: 'Login',       type: 'str'   },
    { key: 'host_name',           label: 'Host',        type: 'str'   },
    { key: 'program_name',        label: 'Program',     type: 'trunc' },
    { key: 'status',              label: 'Status',      type: 'badge' },
    { key: 'command',             label: 'Command',     type: 'str'   },
    { key: 'cpu_time',            label: 'CPU (ms)',    type: 'num'   },
    { key: 'memory_kb',           label: 'Mem (KB)',    type: 'num'   },
    { key: 'elapsed_sec',         label: 'Elapsed (s)', type: 'num'   },
    { key: 'wait_type',           label: 'Wait Type',   type: 'str'   },
    { key: 'wait_time',           label: 'Wait (ms)',   type: 'num'   },
    { key: 'blocking_session_id', label: 'Blocked By',  type: 'zero'  },
    { key: 'last_query',          label: 'Last Query',  type: 'query' },
  ],
  waits: [
    { key: 'wait_type',            label: 'Wait Type',       type: 'str' },
    { key: 'waiting_tasks_count',  label: 'Count',           type: 'num' },
    { key: 'wait_time_ms',         label: 'Total Wait (ms)', type: 'num' },
    { key: 'max_wait_time_ms',     label: 'Max Wait (ms)',   type: 'num' },
    { key: 'signal_wait_time_ms',  label: 'Signal (ms)',     type: 'num' },
  ],
  fileio: [
    { key: 'database_name',     label: 'Database',          type: 'str'   },
    { key: 'file_name',         label: 'File',              type: 'trunc' },
    { key: 'file_type',         label: 'Type',              type: 'str'   },
    { key: 'num_of_reads',      label: 'Reads',             type: 'num'   },
    { key: 'num_of_writes',     label: 'Writes',            type: 'num'   },
    { key: 'kb_read',           label: 'KB Read',           type: 'num'   },
    { key: 'kb_written',        label: 'KB Written',        type: 'num'   },
    { key: 'io_stall_read_ms',  label: 'Read Stall (ms)',   type: 'num'   },
    { key: 'io_stall_write_ms', label: 'Write Stall (ms)',  type: 'num'   },
    { key: 'io_stall',          label: 'Total Stall (ms)',  type: 'num'   },
  ],
  recent: [
    { key: 'avg_elapsed_ms',   label: 'Avg Elapsed (ms)', type: 'dec'   },
    { key: 'avg_cpu_ms',       label: 'Avg CPU (ms)',     type: 'dec'   },
    { key: 'avg_logical_reads',label: 'Avg Reads',        type: 'num'   },
    { key: 'execution_count',  label: 'Executions',       type: 'num'   },
    { key: 'last_executed',    label: 'Last Executed',    type: 'str'   },
    { key: 'query_text',       label: 'Query',            type: 'query' },
  ],
  active: [
    { key: 'session_id',          label: 'Session',     type: 'num'   },
    { key: 'status',              label: 'Status',      type: 'badge' },
    { key: 'command',             label: 'Command',     type: 'str'   },
    { key: 'database_name',       label: 'Database',    type: 'str'   },
    { key: 'cpu_time',            label: 'CPU (ms)',    type: 'num'   },
    { key: 'elapsed_sec',         label: 'Elapsed (s)', type: 'num'   },
    { key: 'reads',               label: 'Reads',       type: 'num'   },
    { key: 'writes',              label: 'Writes',      type: 'num'   },
    { key: 'logical_reads',       label: 'Logical R',   type: 'num'   },
    { key: 'wait_type',           label: 'Wait Type',   type: 'str'   },
    { key: 'wait_time',           label: 'Wait (ms)',   type: 'num'   },
    { key: 'blocking_session_id', label: 'Blocked By',  type: 'zero'  },
    { key: 'query_text',          label: 'Query',       type: 'query' },
  ],
  blocking: [
    { key: 'blocking_session_id', label: 'Blocker',       type: 'num'   },
    { key: 'blocker_login',       label: 'Blocker Login', type: 'str'   },
    { key: 'blocker_host',        label: 'Blocker Host',  type: 'trunc' },
    { key: 'blocker_query',       label: 'Blocker Query', type: 'query' },
    { key: 'blocked_session_id',  label: 'Blocked',       type: 'num'   },
    { key: 'blocked_login',       label: 'Blocked Login', type: 'str'   },
    { key: 'blocked_host',        label: 'Blocked Host',  type: 'trunc' },
    { key: 'wait_type',           label: 'Wait Type',     type: 'str'   },
    { key: 'wait_time',           label: 'Wait (ms)',     type: 'num'   },
    { key: 'elapsed_sec',         label: 'Elapsed (s)',   type: 'num'   },
    { key: 'database_name',       label: 'Database',      type: 'str'   },
    { key: 'blocked_query',       label: 'Blocked Query', type: 'query' },
  ],
  deadlocks: [
    { key: 'deadlock_time', label: 'Time',      type: 'str'   },
    { key: 'process_count', label: 'Processes', type: 'num'   },
    { key: 'spids',         label: 'SPIDs',     type: 'str'   },
    { key: 'login1',        label: 'Login',     type: 'str'   },
    { key: 'host1',         label: 'Host',      type: 'trunc' },
    { key: 'resource_name', label: 'Resource',  type: 'trunc' },
    { key: 'lock_mode',     label: 'Lock Mode', type: 'str'   },
    { key: 'query1',        label: 'Query 1',   type: 'query' },
    { key: 'query2',        label: 'Query 2',   type: 'query' },
  ],
}

export const DEFAULT_SORT = {
  proc:      { col: 'cpu_time',       dir: 'desc' },
  waits:     { col: 'wait_time_ms',   dir: 'desc' },
  fileio:    { col: 'io_stall',       dir: 'desc' },
  recent:    { col: 'avg_elapsed_ms', dir: 'desc' },
  active:    { col: 'elapsed_sec',    dir: 'desc' },
  blocking:  { col: 'wait_time',      dir: 'desc' },
  deadlocks: { col: 'deadlock_time',  dir: 'desc' },
}
